server:
  port: 8404
  
spring:
  application:
    name: georeferenciamento-service

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8302/eureka/
#  instance:
#    hostname: localhost
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: https://sgim-eureka-service.herokuapp.com/
    
ribbon:
  eureka:
    enabled: true            